// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PCConfigurator.Data;

#nullable disable

namespace DIPLOMEN_PROEKT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("PCConfigurator.Models.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FormFactor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportedFormFactors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "NZXT",
                            FormFactor = "",
                            ImageUrl = "...",
                            Name = "NZXT H7 Flow (ATX)",
                            Price = 130m,
                            SupportedFormFactors = "ATX,mATX"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "DeepCool",
                            FormFactor = "",
                            ImageUrl = "...",
                            Name = "DeepCool CC560 V2 (ATX)",
                            Price = 65m,
                            SupportedFormFactors = "ATX,mATX"
                        });
                });

            modelBuilder.Entity("PCConfigurator.Models.GPU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecommendedPSU")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<int>("VRAM")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GPUs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Nvidia",
                            ImageUrl = "https://m.media-amazon.com/images/I/81xU+7F7L7L._AC_SL1500_.jpg",
                            Name = "NVIDIA GeForce RTX 4090 24GB",
                            Price = 1950m,
                            RecommendedPSU = 1000,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Nvidia",
                            ImageUrl = "https://m.media-amazon.com/images/I/71Xf+6pY90L._AC_SL1500_.jpg",
                            Name = "NVIDIA GeForce RTX 4080 SUPER 16GB",
                            Price = 1100m,
                            RecommendedPSU = 850,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Nvidia",
                            ImageUrl = "https://m.media-amazon.com/images/I/71Xf+6pY90L._AC_SL1500_.jpg",
                            Name = "NVIDIA GeForce RTX 4080 16GB",
                            Price = 1050m,
                            RecommendedPSU = 850,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Nvidia",
                            ImageUrl = "https://m.media-amazon.com/images/I/71XmjJ1N7RL._AC_SL1500_.jpg",
                            Name = "NVIDIA GeForce RTX 4070 Ti SUPER 16GB",
                            Price = 880m,
                            RecommendedPSU = 750,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Nvidia",
                            ImageUrl = "https://m.media-amazon.com/images/I/71XmjJ1N7RL._AC_SL1500_.jpg",
                            Name = "NVIDIA GeForce RTX 4070 Ti 12GB",
                            Price = 800m,
                            RecommendedPSU = 750,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Nvidia",
                            ImageUrl = "https://m.media-amazon.com/images/I/71XmjJ1N7RL._AC_SL1500_.jpg",
                            Name = "NVIDIA GeForce RTX 4070 SUPER 12GB",
                            Price = 660m,
                            RecommendedPSU = 700,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Nvidia",
                            ImageUrl = "https://m.media-amazon.com/images/I/71XmjJ1N7RL._AC_SL1500_.jpg",
                            Name = "NVIDIA GeForce RTX 4070 12GB",
                            Price = 600m,
                            RecommendedPSU = 650,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Nvidia",
                            ImageUrl = "https://m.media-amazon.com/images/I/716m2O2GkTL._AC_SL1500_.jpg",
                            Name = "NVIDIA GeForce RTX 4060 Ti 8GB",
                            Price = 410m,
                            RecommendedPSU = 550,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Nvidia",
                            ImageUrl = "https://m.media-amazon.com/images/I/716m2O2GkTL._AC_SL1500_.jpg",
                            Name = "NVIDIA GeForce RTX 4060 8GB",
                            Price = 310m,
                            RecommendedPSU = 550,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Nvidia",
                            ImageUrl = "https://m.media-amazon.com/images/I/81xU+7F7L7L._AC_SL1500_.jpg",
                            Name = "NVIDIA GeForce RTX 3090 Ti 24GB",
                            Price = 1200m,
                            RecommendedPSU = 850,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Nvidia",
                            ImageUrl = "https://m.media-amazon.com/images/I/81xU+7F7L7L._AC_SL1500_.jpg",
                            Name = "NVIDIA GeForce RTX 3090 24GB",
                            Price = 1100m,
                            RecommendedPSU = 850,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Nvidia",
                            ImageUrl = "...",
                            Name = "NVIDIA GeForce RTX 3080 Ti 12GB",
                            Price = 900m,
                            RecommendedPSU = 750,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Nvidia",
                            ImageUrl = "...",
                            Name = "NVIDIA GeForce RTX 3080 10GB",
                            Price = 700m,
                            RecommendedPSU = 750,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Nvidia",
                            ImageUrl = "...",
                            Name = "NVIDIA GeForce RTX 3070 Ti 8GB",
                            Price = 580m,
                            RecommendedPSU = 750,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Nvidia",
                            ImageUrl = "...",
                            Name = "NVIDIA GeForce RTX 3070 8GB",
                            Price = 500m,
                            RecommendedPSU = 650,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Nvidia",
                            ImageUrl = "...",
                            Name = "NVIDIA GeForce RTX 3060 Ti 8GB",
                            Price = 380m,
                            RecommendedPSU = 600,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Nvidia",
                            ImageUrl = "...",
                            Name = "NVIDIA GeForce RTX 3060 12GB",
                            Price = 290m,
                            RecommendedPSU = 550,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Nvidia",
                            ImageUrl = "...",
                            Name = "NVIDIA GeForce RTX 3050 8GB",
                            Price = 230m,
                            RecommendedPSU = 550,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Nvidia",
                            ImageUrl = "...",
                            Name = "NVIDIA GeForce RTX 2080 Ti 11GB",
                            Price = 500m,
                            RecommendedPSU = 650,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Nvidia",
                            ImageUrl = "...",
                            Name = "NVIDIA GeForce RTX 2080 Super",
                            Price = 450m,
                            RecommendedPSU = 650,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Nvidia",
                            ImageUrl = "...",
                            Name = "NVIDIA GeForce RTX 2070 Super",
                            Price = 350m,
                            RecommendedPSU = 650,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 22,
                            Brand = "Nvidia",
                            ImageUrl = "...",
                            Name = "NVIDIA GeForce RTX 2060 Super",
                            Price = 280m,
                            RecommendedPSU = 550,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 23,
                            Brand = "Nvidia",
                            ImageUrl = "...",
                            Name = "NVIDIA GeForce RTX 2060 6GB",
                            Price = 220m,
                            RecommendedPSU = 500,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 24,
                            Brand = "Nvidia",
                            ImageUrl = "...",
                            Name = "NVIDIA GeForce GTX 1660 SUPER",
                            Price = 210m,
                            RecommendedPSU = 450,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Nvidia",
                            ImageUrl = "...",
                            Name = "NVIDIA GeForce GTX 1650 SUPER",
                            Price = 160m,
                            RecommendedPSU = 350,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 26,
                            Brand = "Nvidia",
                            ImageUrl = "...",
                            Name = "NVIDIA GeForce GTX 1630",
                            Price = 130m,
                            RecommendedPSU = 300,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 27,
                            Brand = "Nvidia",
                            ImageUrl = "...",
                            Name = "NVIDIA GeForce GTX 1080 Ti 11GB",
                            Price = 300m,
                            RecommendedPSU = 600,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 28,
                            Brand = "Nvidia",
                            ImageUrl = "...",
                            Name = "NVIDIA GeForce GTX 1080 8GB",
                            Price = 250m,
                            RecommendedPSU = 500,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 29,
                            Brand = "Nvidia",
                            ImageUrl = "...",
                            Name = "NVIDIA GeForce GTX 1070 Ti",
                            Price = 220m,
                            RecommendedPSU = 500,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Nvidia",
                            ImageUrl = "...",
                            Name = "NVIDIA GeForce GTX 1060 6GB",
                            Price = 150m,
                            RecommendedPSU = 400,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 31,
                            Brand = "Nvidia",
                            ImageUrl = "...",
                            Name = "NVIDIA GeForce GTX 1050 Ti 4GB",
                            Price = 110m,
                            RecommendedPSU = 300,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 32,
                            Brand = "Nvidia",
                            ImageUrl = "...",
                            Name = "NVIDIA GeForce GTX 1030 2GB",
                            Price = 80m,
                            RecommendedPSU = 300,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 33,
                            Brand = "Nvidia",
                            ImageUrl = "...",
                            Name = "NVIDIA GeForce GTX 980 Ti",
                            Price = 120m,
                            RecommendedPSU = 600,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 34,
                            Brand = "Nvidia",
                            ImageUrl = "...",
                            Name = "NVIDIA GeForce GTX 970",
                            Price = 90m,
                            RecommendedPSU = 500,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 35,
                            Brand = "Nvidia",
                            ImageUrl = "...",
                            Name = "NVIDIA GeForce GTX 750 Ti",
                            Price = 60m,
                            RecommendedPSU = 300,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 36,
                            Brand = "Nvidia",
                            ImageUrl = "...",
                            Name = "NVIDIA GeForce GT 730 2GB",
                            Price = 55m,
                            RecommendedPSU = 300,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 37,
                            Brand = "Nvidia",
                            ImageUrl = "...",
                            Name = "NVIDIA GeForce GT 710 2GB",
                            Price = 45m,
                            RecommendedPSU = 300,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 38,
                            Brand = "AMD",
                            ImageUrl = "https://m.media-amazon.com/images/I/81sh97S0tWL._AC_SL1500_.jpg",
                            Name = "AMD Radeon RX 7900 XTX 24GB",
                            Price = 1050m,
                            RecommendedPSU = 850,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 39,
                            Brand = "AMD",
                            ImageUrl = "...",
                            Name = "AMD Radeon RX 7900 XT 20GB",
                            Price = 840m,
                            RecommendedPSU = 750,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 40,
                            Brand = "AMD",
                            ImageUrl = "...",
                            Name = "AMD Radeon RX 7800 XT 16GB",
                            Price = 540m,
                            RecommendedPSU = 750,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 41,
                            Brand = "AMD",
                            ImageUrl = "...",
                            Name = "AMD Radeon RX 7700 XT 12GB",
                            Price = 460m,
                            RecommendedPSU = 700,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 42,
                            Brand = "AMD",
                            ImageUrl = "...",
                            Name = "AMD Radeon RX 7600 8GB",
                            Price = 280m,
                            RecommendedPSU = 550,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 43,
                            Brand = "AMD",
                            ImageUrl = "...",
                            Name = "AMD Radeon RX 6950 XT",
                            Price = 690m,
                            RecommendedPSU = 850,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 44,
                            Brand = "AMD",
                            ImageUrl = "...",
                            Name = "AMD Radeon RX 6800 XT",
                            Price = 500m,
                            RecommendedPSU = 750,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 45,
                            Brand = "AMD",
                            ImageUrl = "...",
                            Name = "AMD Radeon RX 6700 XT",
                            Price = 350m,
                            RecommendedPSU = 650,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 46,
                            Brand = "AMD",
                            ImageUrl = "...",
                            Name = "AMD Radeon RX 6600 XT",
                            Price = 260m,
                            RecommendedPSU = 500,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 47,
                            Brand = "AMD",
                            ImageUrl = "...",
                            Name = "AMD Radeon RX 6600",
                            Price = 220m,
                            RecommendedPSU = 450,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 48,
                            Brand = "AMD",
                            ImageUrl = "...",
                            Name = "AMD Radeon RX 5700 XT",
                            Price = 200m,
                            RecommendedPSU = 600,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 49,
                            Brand = "AMD",
                            ImageUrl = "...",
                            Name = "AMD Radeon RX 590 8GB",
                            Price = 130m,
                            RecommendedPSU = 550,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 50,
                            Brand = "AMD",
                            ImageUrl = "...",
                            Name = "AMD Radeon RX 580 8GB",
                            Price = 110m,
                            RecommendedPSU = 500,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 51,
                            Brand = "AMD",
                            ImageUrl = "...",
                            Name = "AMD Radeon RX 570 4GB",
                            Price = 90m,
                            RecommendedPSU = 450,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 52,
                            Brand = "AMD",
                            ImageUrl = "...",
                            Name = "AMD Radeon RX 550 4GB",
                            Price = 70m,
                            RecommendedPSU = 350,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 53,
                            Brand = "AMD",
                            ImageUrl = "...",
                            Name = "AMD Radeon Vega 64",
                            Price = 250m,
                            RecommendedPSU = 750,
                            VRAM = 0
                        },
                        new
                        {
                            Id = 54,
                            Brand = "AMD",
                            ImageUrl = "...",
                            Name = "AMD Radeon HD 7770 1GB",
                            Price = 40m,
                            RecommendedPSU = 450,
                            VRAM = 0
                        });
                });

            modelBuilder.Entity("PCConfigurator.Models.Motherboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FormFactor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MemoryType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Motherboards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Intel",
                            FormFactor = "ATX",
                            ImageUrl = "https://m.media-amazon.com/images/I/81O58vLIDeL._AC_SL1500_.jpg",
                            MemoryType = "DDR5",
                            Name = "ASUS ROG Strix Z790-E Gaming WiFi",
                            Price = 520m,
                            Socket = "LGA1700"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Intel",
                            FormFactor = "ATX",
                            ImageUrl = "...",
                            MemoryType = "DDR5",
                            Name = "GIGABYTE Z790 AORUS Elite AX",
                            Price = 280m,
                            Socket = "LGA1700"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Intel",
                            FormFactor = "ATX",
                            ImageUrl = "...",
                            MemoryType = "DDR5",
                            Name = "MSI MAG Z690 Tomahawk WiFi",
                            Price = 250m,
                            Socket = "LGA1700"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Intel",
                            FormFactor = "mATX",
                            ImageUrl = "...",
                            MemoryType = "DDR5",
                            Name = "ASUS TUF Gaming B760M-Plus WiFi",
                            Price = 180m,
                            Socket = "LGA1700"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Intel",
                            FormFactor = "mATX",
                            ImageUrl = "...",
                            MemoryType = "DDR4",
                            Name = "MSI PRO B760M-A WiFi",
                            Price = 160m,
                            Socket = "LGA1700"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Intel",
                            FormFactor = "mATX",
                            ImageUrl = "...",
                            MemoryType = "DDR4",
                            Name = "GIGABYTE B660M DS3H",
                            Price = 120m,
                            Socket = "LGA1700"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Intel",
                            FormFactor = "mATX",
                            ImageUrl = "...",
                            MemoryType = "DDR4",
                            Name = "ASUS PRIME H610M-K D4",
                            Price = 95m,
                            Socket = "LGA1700"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Intel",
                            FormFactor = "ATX",
                            ImageUrl = "...",
                            MemoryType = "DDR4",
                            Name = "ASUS Z590 Gaming WiFi",
                            Price = 170m,
                            Socket = "LGA1200"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Intel",
                            FormFactor = "ATX",
                            ImageUrl = "...",
                            MemoryType = "DDR4",
                            Name = "MSI Z390-A PRO",
                            Price = 130m,
                            Socket = "LGA1151"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "AMD",
                            FormFactor = "ATX",
                            ImageUrl = "...",
                            MemoryType = "DDR5",
                            Name = "ASUS ROG Crosshair X670E Hero",
                            Price = 650m,
                            Socket = "AM5"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "AMD",
                            FormFactor = "ATX",
                            ImageUrl = "...",
                            MemoryType = "DDR5",
                            Name = "GIGABYTE X670E AORUS Master",
                            Price = 480m,
                            Socket = "AM5"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "AMD",
                            FormFactor = "ATX",
                            ImageUrl = "...",
                            MemoryType = "DDR5",
                            Name = "MSI MPG B650 Carbon WiFi",
                            Price = 300m,
                            Socket = "AM5"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "AMD",
                            FormFactor = "ATX",
                            ImageUrl = "...",
                            MemoryType = "DDR5",
                            Name = "ASRock B650 Steel Legend",
                            Price = 240m,
                            Socket = "AM5"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "AMD",
                            FormFactor = "mATX",
                            ImageUrl = "...",
                            MemoryType = "DDR5",
                            Name = "ASUS PRIME A620M-A",
                            Price = 110m,
                            Socket = "AM5"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "AMD",
                            FormFactor = "ATX",
                            ImageUrl = "...",
                            MemoryType = "DDR4",
                            Name = "ASUS ROG Strix X570-E Gaming",
                            Price = 300m,
                            Socket = "AM4"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "AMD",
                            FormFactor = "ATX",
                            ImageUrl = "...",
                            MemoryType = "DDR4",
                            Name = "MSI MAG B550 Tomahawk",
                            Price = 160m,
                            Socket = "AM4"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "AMD",
                            FormFactor = "ATX",
                            ImageUrl = "...",
                            MemoryType = "DDR4",
                            Name = "ASRock B550 Phantom Gaming",
                            Price = 120m,
                            Socket = "AM4"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "AMD",
                            FormFactor = "mATX",
                            ImageUrl = "...",
                            MemoryType = "DDR4",
                            Name = "Gigabyte B450M DS3H",
                            Price = 80m,
                            Socket = "AM4"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "AMD",
                            FormFactor = "mATX",
                            ImageUrl = "...",
                            MemoryType = "DDR4",
                            Name = "ASUS PRIME A520M-K",
                            Price = 65m,
                            Socket = "AM4"
                        });
                });

            modelBuilder.Entity("PCConfigurator.Models.PSU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<int>("Wattage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PSUs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Corsair",
                            ImageUrl = "https://m.media-amazon.com/images/I/71Xf+6pY90L._AC_SL1500_.jpg",
                            Name = "Corsair RM1000x 1000W 80+ Gold",
                            Price = 190m,
                            Rating = "Gold",
                            Wattage = 1000
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Corsair",
                            ImageUrl = "...",
                            Name = "Corsair RM850x 850W 80+ Gold",
                            Price = 150m,
                            Rating = "Gold",
                            Wattage = 850
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Corsair",
                            ImageUrl = "...",
                            Name = "Corsair RM750x 750W 80+ Gold",
                            Price = 130m,
                            Rating = "Gold",
                            Wattage = 750
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Corsair",
                            ImageUrl = "...",
                            Name = "Corsair CV550 550W 80+ Bronze",
                            Price = 60m,
                            Rating = "Bronze",
                            Wattage = 550
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Seasonic",
                            ImageUrl = "...",
                            Name = "Seasonic Focus GX-850 850W Gold",
                            Price = 150m,
                            Rating = "Gold",
                            Wattage = 850
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Seasonic",
                            ImageUrl = "...",
                            Name = "Seasonic Focus GX-650 650W Gold",
                            Price = 120m,
                            Rating = "Gold",
                            Wattage = 650
                        },
                        new
                        {
                            Id = 7,
                            Brand = "be quiet!",
                            ImageUrl = "...",
                            Name = "be quiet! Pure Power 11 700W Gold",
                            Price = 110m,
                            Rating = "Gold",
                            Wattage = 700
                        },
                        new
                        {
                            Id = 8,
                            Brand = "EVGA",
                            ImageUrl = "...",
                            Name = "EVGA SuperNOVA 850 G5 850W Gold",
                            Price = 145m,
                            Rating = "Gold",
                            Wattage = 850
                        },
                        new
                        {
                            Id = 9,
                            Brand = "EVGA",
                            ImageUrl = "...",
                            Name = "EVGA 600 BR 600W 80+ Bronze",
                            Price = 65m,
                            Rating = "Bronze",
                            Wattage = 600
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Gigabyte",
                            ImageUrl = "...",
                            Name = "Gigabyte P650B 650W 80+ Bronze",
                            Price = 70m,
                            Rating = "Bronze",
                            Wattage = 650
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Thermaltake",
                            ImageUrl = "...",
                            Name = "Thermaltake Smart RGB 600W",
                            Price = 55m,
                            Rating = "Bronze",
                            Wattage = 600
                        });
                });

            modelBuilder.Entity("PCConfigurator.Models.Processor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TDP")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Processors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "AMD",
                            ImageUrl = "https://m.media-amazon.com/images/I/71B9s66H7JL._AC_SL1500_.jpg",
                            Name = "AMD Ryzen 9 7950X3D (4.2GHz) TRAY",
                            Price = 680m,
                            Socket = "AM5",
                            TDP = 120
                        },
                        new
                        {
                            Id = 2,
                            Brand = "AMD",
                            ImageUrl = "https://m.media-amazon.com/images/I/71B9s66H7JL._AC_SL1500_.jpg",
                            Name = "AMD Ryzen 9 7950X (4.5GHz) TRAY",
                            Price = 570m,
                            Socket = "AM5",
                            TDP = 170
                        },
                        new
                        {
                            Id = 3,
                            Brand = "AMD",
                            ImageUrl = "https://m.media-amazon.com/images/I/71B9s66H7JL._AC_SL1500_.jpg",
                            Name = "AMD Ryzen 9 7900X3D (4.4GHz) TRAY",
                            Price = 510m,
                            Socket = "AM5",
                            TDP = 120
                        },
                        new
                        {
                            Id = 4,
                            Brand = "AMD",
                            ImageUrl = "https://m.media-amazon.com/images/I/71B9s66H7JL._AC_SL1500_.jpg",
                            Name = "AMD Ryzen 9 7900X (4.7GHz) TRAY",
                            Price = 450m,
                            Socket = "AM5",
                            TDP = 170
                        },
                        new
                        {
                            Id = 5,
                            Brand = "AMD",
                            ImageUrl = "https://m.media-amazon.com/images/I/71B9s66H7JL._AC_SL1500_.jpg",
                            Name = "AMD Ryzen 9 7900 (3.7GHz) TRAY",
                            Price = 420m,
                            Socket = "AM5",
                            TDP = 65
                        },
                        new
                        {
                            Id = 6,
                            Brand = "AMD",
                            ImageUrl = "https://m.media-amazon.com/images/I/51p6K6N5p1L._AC_SL1000_.jpg",
                            Name = "AMD Ryzen 7 7800X3D (4.2GHz) TRAY",
                            Price = 430m,
                            Socket = "AM5",
                            TDP = 120
                        },
                        new
                        {
                            Id = 7,
                            Brand = "AMD",
                            ImageUrl = "https://m.media-amazon.com/images/I/51p6K6N5p1L._AC_SL1000_.jpg",
                            Name = "AMD Ryzen 7 7700X (4.5GHz) TRAY",
                            Price = 350m,
                            Socket = "AM5",
                            TDP = 105
                        },
                        new
                        {
                            Id = 8,
                            Brand = "AMD",
                            ImageUrl = "https://m.media-amazon.com/images/I/51p6K6N5p1L._AC_SL1000_.jpg",
                            Name = "AMD Ryzen 7 7700 (3.8GHz) TRAY",
                            Price = 320m,
                            Socket = "AM5",
                            TDP = 65
                        },
                        new
                        {
                            Id = 9,
                            Brand = "AMD",
                            ImageUrl = "https://m.media-amazon.com/images/I/61SOfmByXjL._AC_SL1500_.jpg",
                            Name = "AMD Ryzen 5 7600X (4.7GHz) TRAY",
                            Price = 240m,
                            Socket = "AM5",
                            TDP = 105
                        },
                        new
                        {
                            Id = 10,
                            Brand = "AMD",
                            ImageUrl = "https://m.media-amazon.com/images/I/61SOfmByXjL._AC_SL1500_.jpg",
                            Name = "AMD Ryzen 5 7600 (3.8GHz) TRAY",
                            Price = 215m,
                            Socket = "AM5",
                            TDP = 65
                        },
                        new
                        {
                            Id = 11,
                            Brand = "AMD",
                            ImageUrl = "https://m.media-amazon.com/images/I/61SOfmByXjL._AC_SL1500_.jpg",
                            Name = "AMD Ryzen 5 5600X (3.7GHz) TRAY",
                            Price = 155m,
                            Socket = "AM4",
                            TDP = 65
                        },
                        new
                        {
                            Id = 12,
                            Brand = "AMD",
                            ImageUrl = "https://m.media-amazon.com/images/I/61SOfmByXjL._AC_SL1500_.jpg",
                            Name = "AMD Ryzen 5 5600 (3.5GHz) TRAY",
                            Price = 135m,
                            Socket = "AM4",
                            TDP = 65
                        },
                        new
                        {
                            Id = 13,
                            Brand = "AMD",
                            ImageUrl = "https://m.media-amazon.com/images/I/61SOfmByXjL._AC_SL1500_.jpg",
                            Name = "AMD Ryzen 3 4100 (3.8GHz) TRAY",
                            Price = 75m,
                            Socket = "AM4",
                            TDP = 65
                        },
                        new
                        {
                            Id = 14,
                            Brand = "AMD",
                            ImageUrl = "https://m.media-amazon.com/images/I/61SOfmByXjL._AC_SL1500_.jpg",
                            Name = "AMD Ryzen 3 3200G (3.6GHz) TRAY",
                            Price = 85m,
                            Socket = "AM4",
                            TDP = 65
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Intel",
                            ImageUrl = "https://m.media-amazon.com/images/I/61S7Ej68L+L._AC_SL1000_.jpg",
                            Name = "Intel Core i9-14900K (3.2GHz) TRAY",
                            Price = 630m,
                            Socket = "LGA1700",
                            TDP = 125
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Intel",
                            ImageUrl = "https://m.media-amazon.com/images/I/61S7Ej68L+L._AC_SL1000_.jpg",
                            Name = "Intel Core i9-14900KF (3.2GHz) TRAY",
                            Price = 605m,
                            Socket = "LGA1700",
                            TDP = 125
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Intel",
                            ImageUrl = "https://m.media-amazon.com/images/I/61S7Ej68L+L._AC_SL1000_.jpg",
                            Name = "Intel Core i9-13900K (3.0GHz) TRAY",
                            Price = 575m,
                            Socket = "LGA1700",
                            TDP = 125
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Intel",
                            ImageUrl = "https://m.media-amazon.com/images/I/61S7Ej68L+L._AC_SL1000_.jpg",
                            Name = "Intel Core i9-13900KF (3.0GHz) TRAY",
                            Price = 550m,
                            Socket = "LGA1700",
                            TDP = 125
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Intel",
                            ImageUrl = "https://m.media-amazon.com/images/I/61fS0Xp8YpL._AC_SL1000_.jpg",
                            Name = "Intel Core i7-14700K (3.4GHz) TRAY",
                            Price = 440m,
                            Socket = "LGA1700",
                            TDP = 125
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Intel",
                            ImageUrl = "https://m.media-amazon.com/images/I/61fS0Xp8YpL._AC_SL1000_.jpg",
                            Name = "Intel Core i7-14700KF (3.4GHz) TRAY",
                            Price = 415m,
                            Socket = "LGA1700",
                            TDP = 125
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Intel",
                            ImageUrl = "https://m.media-amazon.com/images/I/61fS0Xp8YpL._AC_SL1000_.jpg",
                            Name = "Intel Core i7-13700K (3.4GHz) TRAY",
                            Price = 390m,
                            Socket = "LGA1700",
                            TDP = 125
                        },
                        new
                        {
                            Id = 22,
                            Brand = "Intel",
                            ImageUrl = "https://m.media-amazon.com/images/I/61fS0Xp8YpL._AC_SL1000_.jpg",
                            Name = "Intel Core i7-13700KF (3.4GHz) TRAY",
                            Price = 370m,
                            Socket = "LGA1700",
                            TDP = 125
                        },
                        new
                        {
                            Id = 23,
                            Brand = "Intel",
                            ImageUrl = "https://m.media-amazon.com/images/I/616v8WvV94L._AC_SL1000_.jpg",
                            Name = "Intel Core i5-14600K (3.5GHz) TRAY",
                            Price = 340m,
                            Socket = "LGA1700",
                            TDP = 125
                        },
                        new
                        {
                            Id = 24,
                            Brand = "Intel",
                            ImageUrl = "https://m.media-amazon.com/images/I/616v8WvV94L._AC_SL1000_.jpg",
                            Name = "Intel Core i5-14600KF (3.5GHz) TRAY",
                            Price = 315m,
                            Socket = "LGA1700",
                            TDP = 125
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Intel",
                            ImageUrl = "https://m.media-amazon.com/images/I/616v8WvV94L._AC_SL1000_.jpg",
                            Name = "Intel Core i5-13600K (3.5GHz) TRAY",
                            Price = 310m,
                            Socket = "LGA1700",
                            TDP = 125
                        },
                        new
                        {
                            Id = 26,
                            Brand = "Intel",
                            ImageUrl = "https://m.media-amazon.com/images/I/616v8WvV94L._AC_SL1000_.jpg",
                            Name = "Intel Core i5-13600KF (3.5GHz) TRAY",
                            Price = 290m,
                            Socket = "LGA1700",
                            TDP = 125
                        },
                        new
                        {
                            Id = 27,
                            Brand = "Intel",
                            ImageUrl = "https://m.media-amazon.com/images/I/616v8WvV94L._AC_SL1000_.jpg",
                            Name = "Intel Core i5-12600K (3.7GHz) TRAY",
                            Price = 230m,
                            Socket = "LGA1700",
                            TDP = 125
                        },
                        new
                        {
                            Id = 28,
                            Brand = "Intel",
                            ImageUrl = "https://m.media-amazon.com/images/I/51p6K6N5p1L._AC_SL1000_.jpg",
                            Name = "Intel Core i3-14100 (3.5GHz) TRAY",
                            Price = 160m,
                            Socket = "LGA1700",
                            TDP = 60
                        },
                        new
                        {
                            Id = 29,
                            Brand = "Intel",
                            ImageUrl = "https://m.media-amazon.com/images/I/51p6K6N5p1L._AC_SL1000_.jpg",
                            Name = "Intel Core i3-14100F (3.5GHz) TRAY",
                            Price = 130m,
                            Socket = "LGA1700",
                            TDP = 60
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Intel",
                            ImageUrl = "https://m.media-amazon.com/images/I/51p6K6N5p1L._AC_SL1000_.jpg",
                            Name = "Intel Core i3-13100 (3.4GHz) TRAY",
                            Price = 135m,
                            Socket = "LGA1700",
                            TDP = 60
                        },
                        new
                        {
                            Id = 31,
                            Brand = "Intel",
                            ImageUrl = "https://m.media-amazon.com/images/I/51p6K6N5p1L._AC_SL1000_.jpg",
                            Name = "Intel Core i3-13100F (3.4GHz) TRAY",
                            Price = 110m,
                            Socket = "LGA1700",
                            TDP = 60
                        },
                        new
                        {
                            Id = 32,
                            Brand = "Intel",
                            ImageUrl = "https://m.media-amazon.com/images/I/51p6K6N5p1L._AC_SL1000_.jpg",
                            Name = "Intel Core i3-12100 (3.3GHz) TRAY",
                            Price = 110m,
                            Socket = "LGA1700",
                            TDP = 60
                        },
                        new
                        {
                            Id = 33,
                            Brand = "Intel",
                            ImageUrl = "https://m.media-amazon.com/images/I/51p6K6N5p1L._AC_SL1000_.jpg",
                            Name = "Intel Core i3-12100F (3.3GHz) TRAY",
                            Price = 95m,
                            Socket = "LGA1700",
                            TDP = 60
                        });
                });

            modelBuilder.Entity("PCConfigurator.Models.RAM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("SizeGB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RAMs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Kingston",
                            ImageUrl = "...",
                            Name = "Kingston FURY Beast 32GB (2x16) DDR5 6000MHz",
                            Price = 130m,
                            SizeGB = 32,
                            Type = "DDR5"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Kingston",
                            ImageUrl = "...",
                            Name = "Kingston FURY Beast 16GB (2x8) DDR5 5200MHz",
                            Price = 80m,
                            SizeGB = 16,
                            Type = "DDR5"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Corsair",
                            ImageUrl = "...",
                            Name = "Corsair Vengeance LPX 16GB (2x8) DDR4 3200MHz",
                            Price = 45m,
                            SizeGB = 16,
                            Type = "DDR4"
                        });
                });

            modelBuilder.Entity("PCConfigurator.Models.Storage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("SizeGB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Storages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Samsung",
                            ImageUrl = "...",
                            Name = "Samsung 990 PRO 2TB NVMe",
                            Price = 180m,
                            SizeGB = 2000,
                            Type = "NVMe"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Kingston",
                            ImageUrl = "...",
                            Name = "Kingston NV2 1TB NVMe",
                            Price = 65m,
                            SizeGB = 1000,
                            Type = "NVMe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
